using eforms_middleware.Constants;
using System;
using System.Collections.Generic;
using DoT.Infrastructure.DbModels.Entities;

namespace eforms_middleware.DataModel
{

    public class AdditionalHoursClaimsModel : AllowanceClaimsMain
    {

    }
    public class CasualTimsheetsModel : AllowanceClaimsMain
    {

    }
    public class MotorVehicleAllowanceClaimsModel : AllowanceClaimsMain
    {
        public string makeandmodel { get; set; }
        public string atovehicletype { get; set; }
        public string enginesize { get; set; }
        public string fromlocation { get; set; }
        public string tolocation { get; set; }
        public string metrokms { get; set; }
        public string southwestkms { get; set; }
        public string northwestkms { get; set; }
        public string restofstatekms { get; set; }
        public string towingcaravanortrailer { get; set; }
        public string dailyTotalKms { get; set; }
        public string makeandmodel2 { get; set; }
        public string atovehicletype2 { get; set; }
        public string enginesize2 { get; set; }
        public string fromlocation2 { get; set; }
        public string tolocation2 { get; set; }
        public string metrokms2 { get; set; }
        public string southwestkms2 { get; set; }
        public string northwestkms2 { get; set; }
        public string restofstatekms2 { get; set; }
        public string towingcaravanortrailer2 { get; set; }
        public string dailyTotalKms2 { get; set; }
        public string makeandmodel3 { get; set; }
        public string atovehicletype3 { get; set; }
        public string enginesize3 { get; set; }
        public string fromlocation3 { get; set; }
        public string tolocation3 { get; set; }
        public string metrokms3 { get; set; }
        public string southwestkms3 { get; set; }
        public string northwestkms3 { get; set; }
        public string restofstatekms3 { get; set; }
        public string towingcaravanortrailer3 { get; set; }
        public string dailyTotalKms3 { get; set; }
        public string makeandmodel4 { get; set; }
        public string atovehicletype4 { get; set; }
        public string enginesize4 { get; set; }
        public string fromlocation4 { get; set; }
        public string tolocation4 { get; set; }
        public string metrokms4 { get; set; }
        public string southwestkms4 { get; set; }
        public string northwestkms4 { get; set; }
        public string restofstatekms4 { get; set; }
        public string towingcaravanortrailer4 { get; set; }
        public string dailyTotalKms4 { get; set; }
        public string makeandmodel5 { get; set; }
        public string atovehicletype5 { get; set; }
        public string enginesize5 { get; set; }
        public string fromlocation5 { get; set; }
        public string tolocation5 { get; set; }
        public string metrokms5 { get; set; }
        public string southwestkms5 { get; set; }
        public string northwestkms5 { get; set; }
        public string restofstatekms5 { get; set; }
        public string towingcaravanortrailer5 { get; set; }
        public string dailyTotalKms5 { get; set; }
        public string makeandmodel6 { get; set; }
        public string atovehicletype6 { get; set; }
        public string enginesize6 { get; set; }
        public string fromlocation6 { get; set; }
        public string tolocation6 { get; set; }
        public string metrokms6 { get; set; }
        public string southwestkms6 { get; set; }
        public string northwestkms6 { get; set; }
        public string restofstatekms6 { get; set; }
        public string towingcaravanortrailer6 { get; set; }
        public string dailyTotalKms6 { get; set; }
        public string makeandmodel7 { get; set; }
        public string atovehicletype7 { get; set; }
        public string enginesize7 { get; set; }
        public string fromlocation7 { get; set; }
        public string tolocation7 { get; set; }
        public string metrokms7 { get; set; }
        public string southwestkms7 { get; set; }
        public string northwestkms7 { get; set; }
        public string restofstatekms7 { get; set; }
        public string towingcaravanortrailer7 { get; set; }
        public string dailyTotalKms7 { get; set; }
        public string makeandmodel8 { get; set; }
        public string atovehicletype8 { get; set; }
        public string enginesize8 { get; set; }
        public string fromlocation8 { get; set; }
        public string tolocation8 { get; set; }
        public string metrokms8 { get; set; }
        public string southwestkms8 { get; set; }
        public string northwestkms8 { get; set; }
        public string restofstatekms8 { get; set; }
        public string towingcaravanortrailer8 { get; set; }
        public string dailyTotalKms8 { get; set; }
        public string makeandmodel9 { get; set; }
        public string atovehicletype9 { get; set; }
        public string enginesize9 { get; set; }
        public string fromlocation9 { get; set; }
        public string tolocation9 { get; set; }
        public string metrokms9 { get; set; }
        public string southwestkms9 { get; set; }
        public string northwestkms9 { get; set; }
        public string restofstatekms9 { get; set; }
        public string towingcaravanortrailer9 { get; set; }
        public string dailyTotalKms9 { get; set; }
        public string makeandmodel10 { get; set; }
        public string atovehicletype10 { get; set; }
        public string enginesize10 { get; set; }
        public string fromlocation10 { get; set; }
        public string tolocation10 { get; set; }
        public string metrokms10 { get; set; }
        public string southwestkms10 { get; set; }
        public string northwestkms10 { get; set; }
        public string restofstatekms10 { get; set; }
        public string towingcaravanortrailer10 { get; set; }
        public string dailyTotalKms10 { get; set; }
        public string makeandmodel11 { get; set; }
        public string atovehicletype11 { get; set; }
        public string enginesize11 { get; set; }
        public string fromlocation11 { get; set; }
        public string tolocation11 { get; set; }
        public string metrokms11 { get; set; }
        public string southwestkms11 { get; set; }
        public string northwestkms11 { get; set; }
        public string restofstatekms11 { get; set; }
        public string towingcaravanortrailer11 { get; set; }
        public string dailyTotalKms11 { get; set; }
        public string makeandmodel12 { get; set; }
        public string atovehicletype12 { get; set; }
        public string enginesize12 { get; set; }
        public string fromlocation12 { get; set; }
        public string tolocation12 { get; set; }
        public string metrokms12 { get; set; }
        public string southwestkms12 { get; set; }
        public string northwestkms12 { get; set; }
        public string restofstatekms12 { get; set; }
        public string towingcaravanortrailer12 { get; set; }
        public string dailyTotalKms12 { get; set; }
        public string makeandmodel13 { get; set; }
        public string atovehicletype13 { get; set; }
        public string enginesize13 { get; set; }
        public string fromlocation13 { get; set; }
        public string tolocation13 { get; set; }
        public string metrokms13 { get; set; }
        public string southwestkms13 { get; set; }
        public string northwestkms13 { get; set; }
        public string restofstatekms13 { get; set; }
        public string makeandmodel14 { get; set; }
        public string atovehicletype14 { get; set; }
        public string enginesize14 { get; set; }
        public string fromlocation14 { get; set; }
        public string tolocation14 { get; set; }
        public string metrokms14 { get; set; }
        public string southwestkms14 { get; set; }
        public string northwestkms14 { get; set; }
        public string restofstatekms14 { get; set; }
        public string towingcaravanortrailer14 { get; set; }
        public string dailyTotalKms14 { get; set; }
        public string towingcaravanortrailer13 { get; set; }
        public string dailyTotalKms13 { get; set; }
        public string makeandmodel15 { get; set; }
        public string atovehicletype15 { get; set; }
        public string enginesize15 { get; set; }
        public string fromlocation15 { get; set; }
        public string tolocation15 { get; set; }
        public string metrokms15 { get; set; }
        public string southwestkms15 { get; set; }
        public string northwestkms15 { get; set; }
        public string restofstatekms15 { get; set; }
        public string towingcaravanortrailer15 { get; set; }
        public string dailyTotalKms15 { get; set; }
        public string makeandmodel16 { get; set; }
        public string atovehicletype16 { get; set; }
        public string enginesize16 { get; set; }
        public string fromlocation16 { get; set; }
        public string tolocation16 { get; set; }
        public string metrokms16 { get; set; }
        public string southwestkms16 { get; set; }
        public string northwestkms16 { get; set; }
        public string restofstatekms16 { get; set; }
        public string towingcaravanortrailer16 { get; set; }
        public string dailyTotalKms16 { get; set; }
        public string makeandmodel17 { get; set; }
        public string atovehicletype17 { get; set; }
        public string enginesize17 { get; set; }
        public string fromlocation17 { get; set; }
        public string tolocation17 { get; set; }
        public string metrokms17 { get; set; }
        public string southwestkms17 { get; set; }
        public string northwestkms17 { get; set; }
        public string restofstatekms17 { get; set; }
        public string towingcaravanortrailer17 { get; set; }
        public string dailyTotalKms17 { get; set; }
        public string makeandmodel18 { get; set; }
        public string atovehicletype18 { get; set; }
        public string enginesize18 { get; set; }
        public string fromlocation18 { get; set; }
        public string tolocation18 { get; set; }
        public string metrokms18 { get; set; }
        public string southwestkms18 { get; set; }
        public string northwestkms18 { get; set; }
        public string restofstatekms18 { get; set; }
        public string towingcaravanortrailer18 { get; set; }
        public string dailyTotalKms18 { get; set; }
        public string makeandmodel19 { get; set; }
        public string atovehicletype19 { get; set; }
        public string enginesize19 { get; set; }
        public string fromlocation19 { get; set; }
        public string tolocation19 { get; set; }
        public string metrokms19 { get; set; }
        public string southwestkms19 { get; set; }
        public string northwestkms19 { get; set; }
        public string restofstatekms19 { get; set; }
        public string towingcaravanortrailer19 { get; set; }
        public string dailyTotalKms19 { get; set; }
        public string makeandmodel20 { get; set; }
        public string atovehicletype20 { get; set; }
        public string enginesize20 { get; set; }
        public string fromlocation20 { get; set; }
        public string tolocation20 { get; set; }
        public string metrokms20 { get; set; }
        public string southwestkms20 { get; set; }
        public string northwestkms20 { get; set; }
        public string restofstatekms20 { get; set; }
        public string towingcaravanortrailer20 { get; set; }
        public string dailyTotalKms20 { get; set; }
        public string makeandmodel21 { get; set; }
        public string atovehicletype21 { get; set; }
        public string enginesize21 { get; set; }
        public string fromlocation21 { get; set; }
        public string tolocation21 { get; set; }
        public string metrokms21 { get; set; }
        public string southwestkms21 { get; set; }
        public string northwestkms21 { get; set; }
        public string restofstatekms21 { get; set; }
        public string towingcaravanortrailer21 { get; set; }
        public string dailyTotalKms21 { get; set; }
        public string makeandmodel22 { get; set; }
        public string atovehicletype22 { get; set; }
        public string enginesize22 { get; set; }
        public string fromlocation22 { get; set; }
        public string tolocation22 { get; set; }
        public string metrokms22 { get; set; }
        public string southwestkms22 { get; set; }
        public string northwestkms22 { get; set; }
        public string restofstatekms22 { get; set; }
        public string towingcaravanortrailer22 { get; set; }
        public string dailyTotalKms22 { get; set; }
        public string makeandmodel23 { get; set; }
        public string atovehicletype23 { get; set; }
        public string enginesize23 { get; set; }
        public string fromlocation23 { get; set; }
        public string tolocation23 { get; set; }
        public string metrokms23 { get; set; }
        public string southwestkms23 { get; set; }
        public string northwestkms23 { get; set; }
        public string restofstatekms23 { get; set; }
        public string towingcaravanortrailer23 { get; set; }
        public string dailyTotalKms23 { get; set; }
        public string makeandmodel24 { get; set; }
        public string atovehicletype24 { get; set; }
        public string enginesize24 { get; set; }
        public string fromlocation24 { get; set; }
        public string tolocation24 { get; set; }
        public string metrokms24 { get; set; }
        public string southwestkms24 { get; set; }
        public string northwestkms24 { get; set; }
        public string restofstatekms24 { get; set; }
        public string towingcaravanortrailer24 { get; set; }
        public string dailyTotalKms24 { get; set; }
        public string makeandmodel25 { get; set; }
        public string atovehicletype25 { get; set; }
        public string enginesize25 { get; set; }
        public string fromlocation25 { get; set; }
        public string tolocation25 { get; set; }
        public string metrokms25 { get; set; }
        public string southwestkms25 { get; set; }
        public string northwestkms25 { get; set; }
        public string restofstatekms25 { get; set; }
        public string towingcaravanortrailer25 { get; set; }
        public string dailyTotalKms25 { get; set; }
        
        public string totalkms { get; set; }
    }

    public class OtherAllowanceClaimsModel : AllowanceClaimsMain
    {
        public string allowancetype { get; set; }
        public string hours { get; set; }
        public string allowancetype2 { get; set; }
        public string hours2 { get; set; }
        public string allowancetype3 { get; set; }
        public string hours3 { get; set; }
        public string allowancetype4 { get; set; }
        public string hours4 { get; set; }
        public string allowancetype5 { get; set; }
        public string hours5 { get; set; }
        public string allowancetype6 { get; set; }
        public string hours6 { get; set; }
        public string allowancetype7 { get; set; }
        public string hours7 { get; set; }
        public string allowancetype8 { get; set; }
        public string hours8 { get; set; }
        public string allowancetype9 { get; set; }
        public string hours9 { get; set; }
        public string allowancetype10 { get; set; }
        public string hours10 { get; set; }
        public string allowancetype11 { get; set; }
        public string hours11 { get; set; }
        public string allowancetype12 { get; set; }
        public string hours12 { get; set; }
        public string allowancetype13 { get; set; }
        public string hours13 { get; set; }
        public string allowancetype14 { get; set; }
        public string hours14 { get; set; }
        public string allowancetype15 { get; set; }
        public string hours15 { get; set; }
        public string allowancetype16 { get; set; }
        public string hours16 { get; set; }
        public string allowancetype17 { get; set; }
        public string hours17 { get; set; }
        public string allowancetype18 { get; set; }
        public string hours18 { get; set; }
        public string allowancetype19 { get; set; }
        public string hours19 { get; set; }
        public string allowancetype20 { get; set; }
        public string hours20 { get; set; }
        public string allowancetype21 { get; set; }
        public string hours21 { get; set; }
        public string allowancetype22 { get; set; }
        public string hours22 { get; set; }
        public string allowancetype23 { get; set; }
        public string hours23 { get; set; }
        public string allowancetype24 { get; set; }
        public string hours24 { get; set; }
        public string allowancetype25 { get; set; }
        public string hours25 { get; set; }
        public string allowancetype26 { get; set; }
        public string hours26 { get; set; }
        public string allowancetype27 { get; set; }
        public string hours27 { get; set; }
        public string allowancetype28 { get; set; }
        public string hours28 { get; set; }
        public string allowancetype29 { get; set; }
        public string hours29 { get; set; }
        public string allowancetype30 { get; set; }
        public string hours30 { get; set; }
    }

    public class OutofHoursContactClaimsModel : AllowanceClaimsMain
    {
        public string contacttype { get; set; }
        public string hours { get; set; }
        public string contacttype2 { get; set; }
        public string hours2 { get; set; }
        public string contacttype3 { get; set; }
        public string hours3 { get; set; }
        public string contacttype4 { get; set; }
        public string hours4 { get; set; }
        public string contacttype5 { get; set; }
        public string hours5 { get; set; }
        public string contacttype6 { get; set; }
        public string hours6 { get; set; }
        public string contacttype7 { get; set; }
        public string hours7 { get; set; }
        public string contacttype8 { get; set; }
        public string hours8 { get; set; }
        public string contacttype9 { get; set; }
        public string hours9 { get; set; }
        public string contacttype10 { get; set; }
        public string hours10 { get; set; }
        public string contacttype11 { get; set; }
        public string hours11 { get; set; }
        public string contacttype12 { get; set; }
        public string hours12 { get; set; }
        public string contacttype13 { get; set; }
        public string hours13 { get; set; }
        public string contacttype14 { get; set; }
        public string hours14 { get; set; }
        public string contacttype15 { get; set; }
        public string hours15 { get; set; }
        public string contacttype16 { get; set; }
        public string hours16 { get; set; }
        public string contacttype17 { get; set; }
        public string hours17 { get; set; }
        public string contacttype18 { get; set; }
        public string hours18 { get; set; }
        public string contacttype19 { get; set; }
        public string hours19 { get; set; }
        public string contacttype20 { get; set; }
        public string hours20 { get; set; }
        public string contacttype21 { get; set; }
        public string hours21 { get; set; }
        public string contacttype22 { get; set; }
        public string hours22 { get; set; }
        public string contacttype23 { get; set; }
        public string hours23 { get; set; }
        public string contacttype24 { get; set; }
        public string hours24 { get; set; }
        public string contacttype25 { get; set; }
        public string hours25 { get; set; }
        public string contacttype26 { get; set; }
        public string hours26 { get; set; }
        public string contacttype27 { get; set; }
        public string hours27 { get; set; }
        public string contacttype28 { get; set; }
        public string hours28 { get; set; }
        public string contacttype29 { get; set; }
        public string hours29 { get; set; }
        public string contacttype30 { get; set; }
        public string hours30 { get; set; }
    }

    public class OvertimeClaimsModel : AllowanceClaimsMain
    {
        public string isWeekendPublicHoliday { get; set; }
        public string mealAllowanceBreakfast { get; set; }
        public string mealAllowanceLunch { get; set; }
        public string mealAllowanceDinner { get; set; }
        public string isToilTaken { get; set; }
        public string isClaimExcessTravel { get; set; }
        public string hoursOT150First3HoursRec1 { get; set; }
        public string hoursOT200AfterFirst3HoursRec1 { get; set; }
        public string hoursPH150First7HalfHoursRec1 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec1 { get; set; }
        public string overtimeClaimsPayCodeOT150 { get; set; }
        public string overtimeClaimsPayCodeOT200 { get; set; }
        public string overtimeClaimsPayCodePH150 { get; set; }
        public string overtimeClaimsPayCodeOT250 { get; set; }
        public string overtimeClaimsPayCodeMLBF { get; set; }
        public string overtimeClaimsPayCodeMLLU { get; set; }
        public string overtimeClaimsPayCodeMLDI { get; set; }
        public string overtimeClaimsPayCodeTOIL { get; set; }
        public string isWeekendPublicHoliday2 { get; set; }
        public string mealAllowanceBreakfast2 { get; set; }
        public string mealAllowanceLunch2 { get; set; }
        public string mealAllowanceDinner2 { get; set; }
        public string isToilTaken2 { get; set; }
        public string isClaimExcessTravel2 { get; set; }
        public string hoursOT150First3HoursRec2 { get; set; }
        public string hoursOT200AfterFirst3HoursRec2 { get; set; }
        public string hoursPH150First7HalfHoursRec2 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec2 { get; set; }
        public string overtimeClaimsPayCode2OT150 { get; set; }
        public string overtimeClaimsPayCode2OT200 { get; set; }
        public string overtimeClaimsPayCode2PH150 { get; set; }
        public string overtimeClaimsPayCode2OT250 { get; set; }
        public string overtimeClaimsPayCode2MLBF { get; set; }
        public string overtimeClaimsPayCode2MLLU { get; set; }
        public string overtimeClaimsPayCode2MLDI { get; set; }
        public string overtimeClaimsPayCode2TOIL { get; set; }
        public string isWeekendPublicHoliday3 { get; set; }
        public string mealAllowanceBreakfast3 { get; set; }
        public string mealAllowanceLunch3 { get; set; }
        public string mealAllowanceDinner3 { get; set; }
        public string isToilTaken3 { get; set; }
        public string isClaimExcessTravel3 { get; set; }
        public string hoursOT150First3HoursRec3 { get; set; }
        public string hoursOT200AfterFirst3HoursRec3 { get; set; }
        public string hoursPH150First7HalfHoursRec3 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec3 { get; set; }
        public string overtimeClaimsPayCode3OT150 { get; set; }
        public string overtimeClaimsPayCode3OT200 { get; set; }
        public string overtimeClaimsPayCode3PH150 { get; set; }
        public string overtimeClaimsPayCode3OT250 { get; set; }
        public string overtimeClaimsPayCode3MLBF { get; set; }
        public string overtimeClaimsPayCode3MLLU { get; set; }
        public string overtimeClaimsPayCode3MLDI { get; set; }
        public string overtimeClaimsPayCode3TOIL { get; set; }
        public string isWeekendPublicHoliday4 { get; set; }
        public string mealAllowanceBreakfast4 { get; set; }
        public string mealAllowanceLunch4 { get; set; }
        public string mealAllowanceDinner4 { get; set; }
        public string isToilTaken4 { get; set; }
        public string isClaimExcessTravel4 { get; set; }
        public string hoursOT150First3HoursRec4 { get; set; }
        public string hoursOT200AfterFirst3HoursRec4 { get; set; }
        public string hoursPH150First7HalfHoursRec4 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec4 { get; set; }
        public string overtimeClaimsPayCode4OT150 { get; set; }
        public string overtimeClaimsPayCode4OT200 { get; set; }
        public string overtimeClaimsPayCode4PH150 { get; set; }
        public string overtimeClaimsPayCode4OT250 { get; set; }
        public string overtimeClaimsPayCode4MLBF { get; set; }
        public string overtimeClaimsPayCode4MLLU { get; set; }
        public string overtimeClaimsPayCode4MLDI { get; set; }
        public string overtimeClaimsPayCode4TOIL { get; set; }
        public string isWeekendPublicHoliday5 { get; set; }
        public string mealAllowanceBreakfast5 { get; set; }
        public string mealAllowanceLunch5 { get; set; }
        public string mealAllowanceDinner5 { get; set; }
        public string isToilTaken5 { get; set; }
        public string isClaimExcessTravel5 { get; set; }
        public string hoursOT150First3HoursRec5 { get; set; }
        public string hoursOT200AfterFirst3HoursRec5 { get; set; }
        public string hoursPH150First7HalfHoursRec5 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec5 { get; set; }
        public string overtimeClaimsPayCode5OT150 { get; set; }
        public string overtimeClaimsPayCode5OT200 { get; set; }
        public string overtimeClaimsPayCode5PH150 { get; set; }
        public string overtimeClaimsPayCode5OT250 { get; set; }
        public string overtimeClaimsPayCode5MLBF { get; set; }
        public string overtimeClaimsPayCode5MLLU { get; set; }
        public string overtimeClaimsPayCode5MLDI { get; set; }
        public string overtimeClaimsPayCode5TOIL { get; set; }
        public string isWeekendPublicHoliday6 { get; set; }
        public string mealAllowanceBreakfast6 { get; set; }
        public string mealAllowanceLunch6 { get; set; }
        public string mealAllowanceDinner6 { get; set; }
        public string isToilTaken6 { get; set; }
        public string isClaimExcessTravel6 { get; set; }
        public string hoursOT150First3HoursRec6 { get; set; }
        public string hoursOT200AfterFirst3HoursRec6 { get; set; }
        public string hoursPH150First7HalfHoursRec6 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec6 { get; set; }
        public string overtimeClaimsPayCode6OT150 { get; set; }
        public string overtimeClaimsPayCode6OT200 { get; set; }
        public string overtimeClaimsPayCode6PH150 { get; set; }
        public string overtimeClaimsPayCode6OT250 { get; set; }
        public string overtimeClaimsPayCode6MLBF { get; set; }
        public string overtimeClaimsPayCode6MLLU { get; set; }
        public string overtimeClaimsPayCode6MLDI { get; set; }
        public string overtimeClaimsPayCode6TOIL { get; set; }
        public string isWeekendPublicHoliday7 { get; set; }
        public string mealAllowanceBreakfast7 { get; set; }
        public string mealAllowanceLunch7 { get; set; }
        public string mealAllowanceDinner7 { get; set; }
        public string isToilTaken7 { get; set; }
        public string isClaimExcessTravel7 { get; set; }
        public string hoursOT150First3HoursRec7 { get; set; }
        public string hoursOT200AfterFirst3HoursRec7 { get; set; }
        public string hoursPH150First7HalfHoursRec7 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec7 { get; set; }
        public string overtimeClaimsPayCode7OT150 { get; set; }
        public string overtimeClaimsPayCode7OT200 { get; set; }
        public string overtimeClaimsPayCode7PH150 { get; set; }
        public string overtimeClaimsPayCode7OT250 { get; set; }
        public string overtimeClaimsPayCode7MLBF { get; set; }
        public string overtimeClaimsPayCode7MLLU { get; set; }
        public string overtimeClaimsPayCode7MLDI { get; set; }
        public string overtimeClaimsPayCode7TOIL { get; set; }
        public string isWeekendPublicHoliday8 { get; set; }
        public string mealAllowanceBreakfast8 { get; set; }
        public string mealAllowanceLunch8 { get; set; }
        public string mealAllowanceDinner8 { get; set; }
        public string isToilTaken8 { get; set; }
        public string isClaimExcessTravel8 { get; set; }
        public string hoursOT150First3HoursRec8 { get; set; }
        public string hoursOT200AfterFirst3HoursRec8 { get; set; }
        public string hoursPH150First7HalfHoursRec8 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec8 { get; set; }
        public string overtimeClaimsPayCode8OT150 { get; set; }
        public string overtimeClaimsPayCode8OT200 { get; set; }
        public string overtimeClaimsPayCode8PH150 { get; set; }
        public string overtimeClaimsPayCode8OT250 { get; set; }
        public string overtimeClaimsPayCode8MLBF { get; set; }
        public string overtimeClaimsPayCode8MLLU { get; set; }
        public string overtimeClaimsPayCode8MLDI { get; set; }
        public string overtimeClaimsPayCode8TOIL { get; set; }
        public string isWeekendPublicHoliday9 { get; set; }
        public string mealAllowanceBreakfast9 { get; set; }
        public string mealAllowanceLunch9 { get; set; }
        public string mealAllowanceDinner9 { get; set; }
        public string isToilTaken9 { get; set; }
        public string isClaimExcessTravel9 { get; set; }
        public string hoursOT150First3HoursRec9 { get; set; }
        public string hoursOT200AfterFirst3HoursRec9 { get; set; }
        public string hoursPH150First7HalfHoursRec9 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec9 { get; set; }
        public string overtimeClaimsPayCode9OT150 { get; set; }
        public string overtimeClaimsPayCode9OT200 { get; set; }
        public string overtimeClaimsPayCode9PH150 { get; set; }
        public string overtimeClaimsPayCode9OT250 { get; set; }
        public string overtimeClaimsPayCode9MLBF { get; set; }
        public string overtimeClaimsPayCode9MLLU { get; set; }
        public string overtimeClaimsPayCode9MLDI { get; set; }
        public string overtimeClaimsPayCode9TOIL { get; set; }
        public string isWeekendPublicHoliday10 { get; set; }
        public string mealAllowanceBreakfast10 { get; set; }
        public string mealAllowanceLunch10 { get; set; }
        public string mealAllowanceDinner10 { get; set; }
        public string isToilTaken10 { get; set; }
        public string isClaimExcessTravel10 { get; set; }
        public string hoursOT150First3HoursRec10 { get; set; }
        public string hoursOT200AfterFirst3HoursRec10 { get; set; }
        public string hoursPH150First7HalfHoursRec10 { get; set; }
        public string hoursOT250AfterFirst7HalfHoursRec10 { get; set; }
        public string overtimeClaimsPayCode10OT150 { get; set; }
        public string overtimeClaimsPayCode10OT200 { get; set; }
        public string overtimeClaimsPayCode10PH150 { get; set; }
        public string overtimeClaimsPayCode10OT250 { get; set; }
        public string overtimeClaimsPayCode10MLBF { get; set; }
        public string overtimeClaimsPayCode10MLLU { get; set; }
        public string overtimeClaimsPayCode10MLDI { get; set; }
        public string overtimeClaimsPayCode10TOIL { get; set; }
    }

    public class PenaltyShiftAllowanceClaimsModel : AllowanceClaimsMain
    {
        public string isWeekendPublicHoliday { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec1 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec1 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec1 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec1 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec1 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec1 { get; set; }
        public string isWeekendPublicHoliday2 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec2 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec2 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec2 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec2 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec2 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec2 { get; set; }
        public string isWeekendPublicHoliday3 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec3 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec3 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec3 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec3 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec3 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec3 { get; set; }
        public string isWeekendPublicHoliday4 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec4 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec4 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec4 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec4 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec4 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec4 { get; set; }
        public string isWeekendPublicHoliday5 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec5 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec5 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec5 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec5 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec5 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec5 { get; set; }
        public string isWeekendPublicHoliday6 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec6 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec6 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec6 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec6 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec6 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec6 { get; set; }
        public string isWeekendPublicHoliday7 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec7 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec7 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec7 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec7 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec7 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec7 { get; set; }
        public string isWeekendPublicHoliday8 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec8 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec8 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec8 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec8 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec8 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec8 { get; set; }
        public string isWeekendPublicHoliday9 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec9 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec9 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec9 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec9 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec9 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec9 { get; set; }
        public string isWeekendPublicHoliday10 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH015Rec10 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH020Rec10 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH050Rec10 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSH075Rec10 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSHP50Rec10 { get; set; }
        public string penaltyShiftAllowanceClaimsPayCodeSP150Rec10 { get; set; }
    }

    public class SeaGoingAllowanceClaimModel : AllowanceClaimsMain
    {
        public DateTime? startdateSeaGoingAllowanceClaim { get; set; }
        public DateTime? enddateSeaGoingAllowanceClaim { get; set; }
        public string totaldaysSeaGoingAllowanceClaim { get; set; }
        public string allowancetype { get; set; }
    }


    public class AllowanceClaimsMain
    {
        public DateTime? dateAllowanceClaims { get; set; }
        public string starttimehr { get; set; }
        public string starttimemin { get; set; }
        public string endtimehr { get; set; }
        public string endtimemin { get; set; }
        public string isBreakTaken { get; set; }
        public string breaktakenstarttimehr { get; set; }
        public string breaktakenstarttimemin { get; set; }
        public string breaktakenendtimehr { get; set; }
        public string breaktakenendtimemin { get; set; }
        public string dailyTotalHours { get; set; }
        public DateTime? dateAllowanceClaims2 { get; set; }
        public string starttimehr2 { get; set; }
        public string starttimemin2 { get; set; }
        public string endtimehr2 { get; set; }
        public string endtimemin2 { get; set; }
        public string isBreakTaken2 { get; set; }
        public string breaktakenstarttimehr2 { get; set; }
        public string breaktakenstarttimemin2 { get; set; }
        public string breaktakenendtimehr2 { get; set; }
        public string breaktakenendtimemin2 { get; set; }
        public string dailyTotalHours2 { get; set; }
        public DateTime? dateAllowanceClaims3 { get; set; }
        public string starttimehr3 { get; set; }
        public string starttimemin3 { get; set; }
        public string endtimehr3 { get; set; }
        public string endtimemin3 { get; set; }
        public string isBreakTaken3 { get; set; }
        public string breaktakenstarttimehr3 { get; set; }
        public string breaktakenstarttimemin3 { get; set; }
        public string breaktakenendtimehr3 { get; set; }
        public string breaktakenendtimemin3 { get; set; }
        public string dailyTotalHours3 { get; set; }
        public DateTime? dateAllowanceClaims4 { get; set; }
        public string starttimehr4 { get; set; }
        public string starttimemin4 { get; set; }
        public string endtimehr4 { get; set; }
        public string endtimemin4 { get; set; }
        public string isBreakTaken4 { get; set; }
        public string breaktakenstarttimehr4 { get; set; }
        public string breaktakenstarttimemin4 { get; set; }
        public string breaktakenendtimehr4 { get; set; }
        public string breaktakenendtimemin4 { get; set; }
        public string dailyTotalHours4 { get; set; }
        public DateTime? dateAllowanceClaims5 { get; set; }
        public string starttimehr5 { get; set; }
        public string starttimemin5 { get; set; }
        public string endtimehr5 { get; set; }
        public string endtimemin5 { get; set; }
        public string isBreakTaken5 { get; set; }
        public string breaktakenstarttimehr5 { get; set; }
        public string breaktakenstarttimemin5 { get; set; }
        public string breaktakenendtimehr5 { get; set; }
        public string breaktakenendtimemin5 { get; set; }
        public string dailyTotalHours5 { get; set; }
        public DateTime? dateAllowanceClaims6 { get; set; }
        public string starttimehr6 { get; set; }
        public string starttimemin6 { get; set; }
        public string endtimehr6 { get; set; }
        public string endtimemin6 { get; set; }
        public string isBreakTaken6 { get; set; }
        public string breaktakenstarttimehr6 { get; set; }
        public string breaktakenstarttimemin6 { get; set; }
        public string breaktakenendtimehr6 { get; set; }
        public string breaktakenendtimemin6 { get; set; }
        public string dailyTotalHours6 { get; set; }
        public DateTime? dateAllowanceClaims7 { get; set; }
        public string starttimehr7 { get; set; }
        public string starttimemin7 { get; set; }
        public string endtimehr7 { get; set; }
        public string endtimemin7 { get; set; }
        public string isBreakTaken7 { get; set; }
        public string breaktakenstarttimehr7 { get; set; }
        public string breaktakenstarttimemin7 { get; set; }
        public string breaktakenendtimehr7 { get; set; }
        public string breaktakenendtimemin7 { get; set; }
        public string dailyTotalHours7 { get; set; }
        public DateTime? dateAllowanceClaims8 { get; set; }
        public string starttimehr8 { get; set; }
        public string starttimemin8 { get; set; }
        public string endtimehr8 { get; set; }
        public string endtimemin8 { get; set; }
        public string isBreakTaken8 { get; set; }
        public string breaktakenstarttimehr8 { get; set; }
        public string breaktakenstarttimemin8 { get; set; }
        public string breaktakenendtimehr8 { get; set; }
        public string breaktakenendtimemin8 { get; set; }
        public string dailyTotalHours8 { get; set; }
        public DateTime? dateAllowanceClaims9 { get; set; }
        public string starttimehr9 { get; set; }
        public string starttimemin9 { get; set; }
        public string endtimehr9 { get; set; }
        public string endtimemin9 { get; set; }
        public string isBreakTaken9 { get; set; }
        public string breaktakenstarttimehr9 { get; set; }
        public string breaktakenstarttimemin9 { get; set; }
        public string breaktakenendtimehr9 { get; set; }
        public string breaktakenendtimemin9 { get; set; }
        public string dailyTotalHours9 { get; set; }

        public DateTime? dateAllowanceClaims10 { get; set; }
        public string starttimehr10 { get; set; }
        public string starttimemin10 { get; set; }
        public string endtimehr10 { get; set; }
        public string endtimemin10 { get; set; }
        public string isBreakTaken10 { get; set; }
        public string breaktakenstarttimehr10 { get; set; }
        public string breaktakenstarttimemin10 { get; set; }
        public string breaktakenendtimehr10 { get; set; }
        public string breaktakenendtimemin10 { get; set; }
        public string dailyTotalHours10 { get; set; }

        public DateTime? dateAllowanceClaims11 { get; set; }
        public string starttimehr11 { get; set; }
        public string starttimemin11 { get; set; }
        public string endtimehr11 { get; set; }
        public string endtimemin11 { get; set; }
        public string isBreakTaken11 { get; set; }
        public string breaktakenstarttimehr11 { get; set; }
        public string breaktakenstarttimemin11 { get; set; }
        public string breaktakenendtimehr11 { get; set; }
        public string breaktakenendtimemin11 { get; set; }
        public string dailyTotalHours11 { get; set; }

        public DateTime? dateAllowanceClaims12 { get; set; }
        public string starttimehr12 { get; set; }
        public string starttimemin12 { get; set; }
        public string endtimehr12 { get; set; }
        public string endtimemin12 { get; set; }
        public string isBreakTaken12 { get; set; }
        public string breaktakenstarttimehr12 { get; set; }
        public string breaktakenstarttimemin12 { get; set; }
        public string breaktakenendtimehr12 { get; set; }
        public string breaktakenendtimemin12 { get; set; }
        public string dailyTotalHours12 { get; set; }

        public DateTime? dateAllowanceClaims13 { get; set; }
        public string starttimehr13 { get; set; }
        public string starttimemin13 { get; set; }
        public string endtimehr13 { get; set; }
        public string endtimemin13 { get; set; }
        public string isBreakTaken13 { get; set; }
        public string breaktakenstarttimehr13 { get; set; }
        public string breaktakenstarttimemin13 { get; set; }
        public string breaktakenendtimehr13 { get; set; }
        public string breaktakenendtimemin13 { get; set; }
        public string dailyTotalHours13 { get; set; }

        public DateTime? dateAllowanceClaims14 { get; set; }
        public string starttimehr14 { get; set; }
        public string starttimemin14 { get; set; }
        public string endtimehr14 { get; set; }
        public string endtimemin14 { get; set; }
        public string isBreakTaken14 { get; set; }
        public string breaktakenstarttimehr14 { get; set; }
        public string breaktakenstarttimemin14 { get; set; }
        public string breaktakenendtimehr14 { get; set; }
        public string breaktakenendtimemin14 { get; set; }
        public string dailyTotalHours14 { get; set; }


        public DateTime? dateAllowanceClaims15 { get; set; }
        public string starttimehr15 { get; set; }
        public string starttimemin15 { get; set; }
        public string endtimehr15 { get; set; }
        public string endtimemin15 { get; set; }
        public string isBreakTaken15 { get; set; }
        public string breaktakenstarttimehr15 { get; set; }
        public string breaktakenstarttimemin15 { get; set; }
        public string breaktakenendtimehr15 { get; set; }
        public string breaktakenendtimemin15 { get; set; }
        public string dailyTotalHours15 { get; set; }

        public DateTime? dateAllowanceClaims16 { get; set; }
        public string starttimehr16 { get; set; }
        public string starttimemin16 { get; set; }
        public string endtimehr16 { get; set; }
        public string endtimemin16 { get; set; }
        public string isBreakTaken16 { get; set; }
        public string breaktakenstarttimehr16 { get; set; }
        public string breaktakenstarttimemin16 { get; set; }
        public string breaktakenendtimehr16 { get; set; }
        public string breaktakenendtimemin16 { get; set; }
        public string dailyTotalHours16 { get; set; }

        public DateTime? dateAllowanceClaims17 { get; set; }
        public string starttimehr17 { get; set; }
        public string starttimemin17 { get; set; }
        public string endtimehr17 { get; set; }
        public string endtimemin17 { get; set; }
        public string isBreakTaken17 { get; set; }
        public string breaktakenstarttimehr17 { get; set; }
        public string breaktakenstarttimemin17 { get; set; }
        public string breaktakenendtimehr17 { get; set; }
        public string breaktakenendtimemin17 { get; set; }
        public string dailyTotalHours17 { get; set; }

        public DateTime? dateAllowanceClaims18 { get; set; }
        public string starttimehr18 { get; set; }
        public string starttimemin18 { get; set; }
        public string endtimehr18 { get; set; }
        public string endtimemin18 { get; set; }
        public string isBreakTaken18 { get; set; }
        public string breaktakenstarttimehr18 { get; set; }
        public string breaktakenstarttimemin18 { get; set; }
        public string breaktakenendtimehr18 { get; set; }
        public string breaktakenendtimemin18 { get; set; }
        public string dailyTotalHours18 { get; set; }

        public DateTime? dateAllowanceClaims19 { get; set; }
        public string starttimehr19 { get; set; }
        public string starttimemin19 { get; set; }
        public string endtimehr19 { get; set; }
        public string endtimemin19 { get; set; }
        public string isBreakTaken19 { get; set; }
        public string breaktakenstarttimehr19 { get; set; }
        public string breaktakenstarttimemin19 { get; set; }
        public string breaktakenendtimehr19 { get; set; }
        public string breaktakenendtimemin19 { get; set; }
        public string dailyTotalHours19 { get; set; }

        public DateTime? dateAllowanceClaims20 { get; set; }
        public string starttimehr20 { get; set; }
        public string starttimemin20 { get; set; }
        public string endtimehr20 { get; set; }
        public string endtimemin20 { get; set; }
        public string isBreakTaken20 { get; set; }
        public string breaktakenstarttimehr20 { get; set; }
        public string breaktakenstarttimemin20 { get; set; }
        public string breaktakenendtimehr20 { get; set; }
        public string breaktakenendtimemin20 { get; set; }
        public string dailyTotalHours20 { get; set; }

        public DateTime? dateAllowanceClaims21 { get; set; }
        public string starttimehr21 { get; set; }
        public string starttimemin21 { get; set; }
        public string endtimehr21 { get; set; }
        public string endtimemin21 { get; set; }
        public string isBreakTaken21 { get; set; }
        public string breaktakenstarttimehr21 { get; set; }
        public string breaktakenstarttimemin21 { get; set; }
        public string breaktakenendtimehr21 { get; set; }
        public string breaktakenendtimemin21 { get; set; }
        public string dailyTotalHours21 { get; set; }

        public DateTime? dateAllowanceClaims22 { get; set; }
        public string starttimehr22 { get; set; }
        public string starttimemin22 { get; set; }
        public string endtimehr22 { get; set; }
        public string endtimemin22 { get; set; }
        public string isBreakTaken22 { get; set; }
        public string breaktakenstarttimehr22 { get; set; }
        public string breaktakenstarttimemin22 { get; set; }
        public string breaktakenendtimehr22 { get; set; }
        public string breaktakenendtimemin22 { get; set; }
        public string dailyTotalHours22 { get; set; }

        public DateTime? dateAllowanceClaims23 { get; set; }
        public string starttimehr23 { get; set; }
        public string starttimemin23 { get; set; }
        public string endtimehr23 { get; set; }
        public string endtimemin23 { get; set; }
        public string isBreakTaken23 { get; set; }
        public string breaktakenstarttimehr23 { get; set; }
        public string breaktakenstarttimemin23 { get; set; }
        public string breaktakenendtimehr23 { get; set; }
        public string breaktakenendtimemin23 { get; set; }
        public string dailyTotalHours23 { get; set; }

        public DateTime? dateAllowanceClaims24 { get; set; }
        public string starttimehr24 { get; set; }
        public string starttimemin24 { get; set; }
        public string endtimehr24 { get; set; }
        public string endtimemin24 { get; set; }
        public string isBreakTaken24 { get; set; }
        public string breaktakenstarttimehr24 { get; set; }
        public string breaktakenstarttimemin24 { get; set; }
        public string breaktakenendtimehr24 { get; set; }
        public string breaktakenendtimemin24 { get; set; }
        public string dailyTotalHours24 { get; set; }

        public DateTime? dateAllowanceClaims25 { get; set; }
        public string starttimehr25 { get; set; }
        public string starttimemin25 { get; set; }
        public string endtimehr25 { get; set; }
        public string endtimemin25 { get; set; }
        public string isBreakTaken25 { get; set; }
        public string breaktakenstarttimehr25 { get; set; }
        public string breaktakenstarttimemin25 { get; set; }
        public string breaktakenendtimehr25 { get; set; }
        public string breaktakenendtimemin25 { get; set; }
        public string dailyTotalHours25 { get; set; }

        public DateTime? dateAllowanceClaims26 { get; set; }
        public string starttimehr26 { get; set; }
        public string starttimemin26 { get; set; }
        public string endtimehr26 { get; set; }
        public string endtimemin26 { get; set; }
        public string isBreakTaken26 { get; set; }
        public string breaktakenstarttimehr26 { get; set; }
        public string breaktakenstarttimemin26 { get; set; }
        public string breaktakenendtimehr26 { get; set; }
        public string breaktakenendtimemin26 { get; set; }
        public string dailyTotalHours26 { get; set; }

        public DateTime? dateAllowanceClaims27 { get; set; }
        public string starttimehr27 { get; set; }
        public string starttimemin27 { get; set; }
        public string endtimehr27 { get; set; }
        public string endtimemin27 { get; set; }
        public string isBreakTaken27 { get; set; }
        public string breaktakenstarttimehr27 { get; set; }
        public string breaktakenstarttimemin27 { get; set; }
        public string breaktakenendtimehr27 { get; set; }
        public string breaktakenendtimemin27 { get; set; }
        public string dailyTotalHours27 { get; set; }

        public DateTime? dateAllowanceClaims28 { get; set; }
        public string starttimehr28 { get; set; }
        public string starttimemin28 { get; set; }
        public string endtimehr28 { get; set; }
        public string endtimemin28 { get; set; }
        public string isBreakTaken28 { get; set; }
        public string breaktakenstarttimehr28 { get; set; }
        public string breaktakenstarttimemin28 { get; set; }
        public string breaktakenendtimehr28 { get; set; }
        public string breaktakenendtimemin28 { get; set; }
        public string dailyTotalHours28 { get; set; }

        public DateTime? dateAllowanceClaims29 { get; set; }
        public string starttimehr29 { get; set; }
        public string starttimemin29 { get; set; }
        public string endtimehr29 { get; set; }
        public string endtimemin29 { get; set; }
        public string isBreakTaken29 { get; set; }
        public string breaktakenstarttimehr29 { get; set; }
        public string breaktakenstarttimemin29 { get; set; }
        public string breaktakenendtimehr29 { get; set; }
        public string breaktakenendtimemin29 { get; set; }
        public string dailyTotalHours29 { get; set; }

        public DateTime? dateAllowanceClaims30 { get; set; }
        public string starttimehr30 { get; set; }
        public string starttimemin30 { get; set; }
        public string endtimehr30 { get; set; }
        public string endtimemin30 { get; set; }
        public string isBreakTaken30 { get; set; }
        public string breaktakenstarttimehr30 { get; set; }
        public string breaktakenstarttimemin30 { get; set; }
        public string breaktakenendtimehr30 { get; set; }
        public string breaktakenendtimemin30 { get; set; }
        public string dailyTotalHours30 { get; set; }


        public string totalBreakTimeHours { get; set; }
        public string totalHours { get; set; }
        public string ReasonForRejection { get; set; }
        public string additionalCommentsAllowanceClaims { get; set; }
        public string fundAllowanceClaims { get; set; }
        public string costcentreAllowanceClaims { get; set; }
        public string accountAllowanceClaims { get; set; }
        public string locationAllowanceClaims { get; set; }
        public string activityAllowanceClaims { get; set; }
        public string projectAllowanceClaims { get; set; }
        public UserIdentifier[] additionalNotificationRecipients { get; set; }
        public string isAccepted { get; set; }
        public string isCostcentreOverride { get; set; }
        public IList<AttachmentResult> attachments { get; set; } = new List<AttachmentResult>();
    }

}