namespace eforms_middleware.Constants
{
    public enum FormStatus
    {
        Submitted = 1,
        Unsubmitted = 2,
        Approved = 3,
        Completed = 4,
        Endorsed = 5,
        Delegate = 6,
        Delegated = 7,
        DelegationApproved,
        Rejected,
        Recall,
        Recalled,
        IndependentReview = 12,
        IndependentReviewCompleted,
        IndependentReviewApproved,
        Requestor,
        Withdraw,
        Escalated,
        Cancelled,
        SubmittedAndEndorsed,
        Reject,
        Complete,
        Approve,
        Saved,
        Allocate,
        Cancel,
        Allocated,
        Close,
        OnBehalf,
        AssignToBackup,
        Reconsiled,
        Attachment,
        Save
    }

    public enum EmailSendType
    {
        Submitter,
        RequestorManager,
        OnBehalf,
        Rejected,
        Cancelled,
        Completed,
        Escalated,
        Delegated,
        Group,
        Approved,
        Reconsile,
        Recalled,
        PrivateVehicle,
        Tier3,
        Tier2,
        Tier1,
        None,
        Saved,
        Created,
        RecalledGroup,
        ReminderNotificationToRequestorsManager,
        EscalatedNotificationRequestorsMgrsMgr,
        EscalatedReminderNotificationRequestorsMgrsMgr,
        EscalationNotificationToPODeFormsBusinessAdminsGroup,
        MgrRejectedNotificationToRequestor,
        ManagerApproveNotificationToRequestor,
        LineMgrsMgrRejectedNotificationToRequestor,
        ESORejectedNotificationToRequestor,
        DelegatedNotificationToDelegatedMgr,
        RecalledNotificationToRequestor,
        RecalledNotificationToRequestorsLineMgrsMgr,
        RegionalManager,
        RequestorManagerReconsile,
        PODEscalate,
        ReadyToReconsileOwner,
        Tier2Manager,
        FinanceTeam,
        TravelHelpfulTips,
        AdditionalApprovalLineManager
    }
}